version: "3.7"
 
services: 
  mariadb_fct:
    container_name: mariadb_fct
    image: mariadb:latest
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: desafio3
      MYSQL_USER: usuario
      MYSQL_PASSWORD: Chubaca2020
      MYSQL_ROOT_PASSWORD: Chubaca2020
    ports:
      - 3316:3306
    networks:
      - laravel
        
  api_laravel_fct:
    container_name: api_laravel_fct
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./storage:/var/www/html/storage
    ports:
      - 8085:80
    depends_on: 
      - 'mariadb_fct'
    networks:
      - laravel

networks:
  laravel: